workflows:
  ios-workflow:
    name: iOS Build and Publish
    environment:
      xcode: latest       # Используем последнюю версию Xcode
      cocoapods: default  # Стандартный CocoaPods (если потребуется)
    scripts:
      - name: Show available destinations
        script: |
          xcodebuild -scheme "MyApp" -showdestinations
      - name: Install dependencies
        script: |
          echo "No additional dependencies to install"
      - name: Build the app
        script: |
          xcodebuild clean archive \
            -scheme "MyApp" \
            -destination "generic/platform=iOS" \
            -archivePath ./build/MyApp.xcarchive
      - name: Create .ipa file
        script: |
          xcodebuild -exportArchive \
            -archivePath ./build/MyApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath ./build
    artifacts:
      - build/*.ipa
