workflows:
  ios-workflow:
    name: iOS Build and Publish
    environment:
      xcode: latest
    scripts:
      - name: Show available schemes
        script: |
          xcodebuild -list
      - name: Build the app
        script: |
          xcodebuild clean archive \
            -scheme "PSalp" \
            -destination "generic/platform=iOS" \
            -archivePath ./build/PSalp.xcarchive
      - name: Create .ipa file
        script: |
          xcodebuild -exportArchive \
            -archivePath ./build/PSalp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath ./build
    artifacts:
      - build/*.ipa
